# Site settings
title: Shubham Kaushik
twitter_username: shubhamk00020
name: Shubham Kaushik

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
#  - title: Blog
#    url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/shubham-sudo
 - title: StackOverflow
   url: https://stackoverflow.com/users/9536331/shubham-kaushik
#  - title: DZone
#    url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/shubham-kaushik-a75204110/

#Any buzzword skills you want to include
skills:
 - Python
 - Django
 - Django-REST
 - Microservices
 - API design
 - SQL
 - Object Oriented Programming
 - Algorithms and Data Structure

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Project Engineer
   start: 2018
   end: Ongoing
   employer: Wipro Limited
   description: I am responsible for developing several API's using Django, Django-REST framework of python.

#Education is required
education:
 - level: Bachelor of Technology (B.Tech)
   date: 2018
   subject: Computer Science & Engineering
   school: University Institute of Engineering and Technology
 - level: Intermediate
   date: 2014
   subject: 
   school: Rishikul Vidyapeeth Sonipat
 - level: Matriculation
   subject: 
   date: 2012
   school: Rishikul Vidyapeeth Sonipat 

#This section is optional (as is the image link below)
certifications:
  - title: Python Programming Track
    organization: DataCamp
    link: https://www.datacamp.com/statement-of-accomplishment/track/5c7d7a07e88eef902cc101bc72ebf219dc312b1c
    date: October, 2018
  - title: Certificate of Experience
    organization: SOPO INTERNET PRIVATE LIMITED
    link: /#
    date: March, 2017
  - title: Programming in Java
    organization: Oracle Workforce Development Program
    link: /#
    date: May, 2016

#List of interesting Github repo/projects to include - optional
github:
 - shubham-sudo/Django_Proj
 - shubham-sudo/Proj_Python
 - shubham-sudo/E-Commerce

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/9536331/shubham-kaushik
   flairimageurl: https://stackoverflow.com/users/flair/9536331.png

intro: |
  I am an innovative software developer with 2 years of experience in developing API's, web and desktop application for internal use to clients purposes.

  Currently, I am a project engineer at WIPRO and a part of digital team. Here, I am responsible for designing several API's which helps in processing data after getting it from several sources and return output back to the caller. This will is used for scheduling several jobs for automating many tasks which is currently being handled by a large team manually.

  Before this, I was a part of cyber defense team for automating several tasks like sending automated mails or analyse logs. I also enhanced and rebuild the anomaly detector which helps in finding anomalies on the network or in the systems.
